# Generated by Django 2.0.4 on 2018-06-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('date_of_birthd', models.DateField(default=None, null=True)),
                ('date_of_death', models.DateField(default=None, null=True)),
                ('country', models.CharField(default=None, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('year_publish', models.IntegerField(default=None, null=True)),
                ('intro_images', models.CharField(max_length=256)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('count_page', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('disslike', models.IntegerField(default=0)),
                ('id_author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Autors')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publishing_house',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('address', models.CharField(default=None, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='id_genre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Genre'),
        ),
        migrations.AddField(
            model_name='books',
            name='id_publishing_house',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Publishing_house'),
        ),
    ]
