# Generated by Django 2.0.4 on 2018-06-03 10:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_booking', models.DateTimeField(auto_now_add=True)),
                ('reserved_until', models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 5, 13, 32, 25, 316742))),
                ('id_book', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
                ('id_reader', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_of_issue', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField()),
                ('return_to', models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 3, 13, 32, 25, 317743))),
                ('id_book', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
                ('id_reader', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
