# Generated by Django 2.0.4 on 2018-06-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64)),
                ('login', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=64, null=True)),
                ('adress', models.CharField(max_length=64)),
                ('telephone', models.CharField(max_length=64)),
                ('date_of_reg', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
